package com.shatteredpixel.shatteredpixeldungeon.scenes;
import com.shatteredpixel.shatteredpixeldungeon.Assets;import com.shatteredpixel.shatteredpixeldungeon.GamesInProgress;import com.shatteredpixel.shatteredpixeldungeon.LedgerFlow;import com.watabou.input.PointerEvent;import com.watabou.noosa.Camera;import com.watabou.noosa.Game;import com.watabou.noosa.Image;import com.watabou.noosa.PointerArea;import com.watabou.noosa.audio.Sample;import com.watabou.noosa.tweeners.Tweener;
public class LedgerIntroScene extends PixelScene{
 private static final String CLOSED="interfaces/echoes/ledger_closed.png";private Image closedBook,openBook;private PointerArea input;private float time,closedScale,openScale;
 @Override public void create(){super.create();uiCamera.visible=false;int w=Camera.main.width,h=Camera.main.height;openBook=LedgerEnvironment.addOpenBook(this);openScale=openBook.scale.x;openBook.alpha(0);closedBook=new Image(CLOSED);closedScale=Math.min(w*.46f/closedBook.width,h*.58f/closedBook.height);closedBook.scale.set(closedScale);center(closedBook);add(closedBook);input=new PointerArea(closedBook.x-5,closedBook.y-5,closedBook.width()+10,closedBook.height()+10){@Override protected void onClick(PointerEvent e){open();}};add(input);fadeIn();}
 @Override public void update(){super.update();time+=Game.elapsed;if(input.active)closedBook.brightness(1f+(float)Math.sin(time*2.1f)*.025f);}
 private void open(){if(!input.active)return;input.active=false;Sample.INSTANCE.play(Assets.Sounds.OPEN,.55f,.92f);add(new Tweener(this,.72f){@Override protected void updateValues(float p){float close=Math.min(1f,p/.48f);closedBook.alpha(1f-close);closedBook.scale.set(closedScale*(1f-.18f*close),closedScale*(1f+.03f*close));center(closedBook);float reveal=Math.max(0f,Math.min(1f,(p-.18f)/.82f));openBook.alpha(reveal);openBook.scale.set(openScale*(.92f+.08f*reveal));center(openBook);}@Override protected void onComplete(){if(GamesInProgress.checkAll().isEmpty()){LedgerFlow.resetDraft();Game.switchScene(LedgerHeroScene.class);}else Game.switchScene(LedgerRecordsScene.class);}});}
 private void center(Image image){image.x=(Camera.main.width-image.width())/2f;image.y=(Camera.main.height-image.height())/2f;PixelScene.align(image);}
}
