package com.shatteredpixel.shatteredpixeldungeon.scenes;

import com.badlogic.gdx.graphics.Pixmap;
import com.watabou.noosa.Image;

/**
 * Embedded palette artwork for the Echoes title flow.
 * Generated from the approved pixel-art source so repository text-only
 * transports cannot corrupt or truncate the image bytes.
 */
final class LedgerClosedArtwork {

    private static final int WIDTH = 128;
    private static final int HEIGHT = 85;
    private static final String SYMBOLS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef";

    private static final int[] PALETTE = new int[]{
            0x92642FFF, 0x563417FF, 0x4C290FFF, 0x3F2511FF, 0x3A1F0DFF, 0x321B0EFF, 0x2E190EFF, 0x2A190DFF, 0x2B170FFF, 0x27160CFF, 0x26150DFF, 0x21140BFF, 0x20120AFF, 0x1C120AFF, 0x1A1009FF, 0x170F09FF, 0x150E09FF, 0x140C08FF, 0x120D0AFF, 0x110C08FF, 0x100B08FF, 0x0F0A07FF, 0x0C0A08FF, 0x0A0806FF, 0x080706FF, 0x050606FF, 0x050505FF, 0x040506FF, 0x040505FF, 0x040504FF, 0x030505FF, 0x030304FF
    };

    private static final String PIXELS =
            "caabbcaaaaaaaddaaaaaZZZZaaaaaaZaaaaaacaaacabaacacaaacaccccdccZcaccbccacccaacaaaccbcbbZbcaccbcccbbZcccccbbbbcZZcbZbbcZbbbcbZbbbbZ" +
            "acaaccaaaaadaaaadaaaZaZaaYaadaaaaaaaacaadcdacccdaccccccaZaaaaZaaaaaZZaaacdeccccccccccaccfccccccccccccccccccccccebcbbZbbbeebbbbbZ" +
            "aaZadccaacaadaaaddaaaaZaaaZZZZadddcaadcaaddcdaffdaaaaceaYYYYYXYXXWWXYXXYaYXYYYZccddcaeeZYcaccfecccccccccccccccccccbbbccbccbcbbbc" +
            "acaaaaddcaaaaaaaaaYaYYZYYYZYYYYXXXYZaacZYXadaaYXYccaYXYYYYXWWVVVUUVWYYaYYXXXVWXWWVVVXYYYZccecYYZcccccccccccccbbcccbccbccccbbcbcc" +
            "acaaccaadcaacZacaaYXYYVYaXVXZYYXYYYYYXWVVVWYddZYXYVXYXXVVXXWXYYYYYXWVYYYYYXXWUVUWXVWXXXYXYXYaYYYYZcZYcdccccccccZbcccccecZccccbbc" +
            "aaaaaaaacaaaaaaYVVVWTTTVUVVWVXWWXVVVYXXYXVVYYYYYYYXWWWVVWWWXWWWXXWXWUUTXYXXXYXYVWZWXWWWWVUWXXYZeccccdacaceffeccbccccecccbbcccacc" +
            "aacacaaaddcacZYWVVVRPOOONNOOMOOTVVUVVWXXVRQRUUUURTRQRPQQQQQTTUTQQONONOOPPOPQQQQQQSTUUTTVVXXYWXYYYXXacceeeYYYYfeccccccccccbbcbccc" +
            "aacaaaaaaXXZXWWXVQONNMMNPORRRUUTTVURQPOPPQQRTTUUUUTRQRRQPPNOOOOPQQTTSUTTUTSRRTQQQPPPRTTRTQORUWWVXYcYXXXXXUXYZYYYebeecccecccccccc" +
            "bcccdaacYWVVRPPPOOMLLMLMMOOOPPNNMLLMMMMMNNNOOOONOOOPPPPQQOOPOOOOPOQPPQQQPPPPQPQTSQQQSTSQQQQRQQQRRTURTVXWWUVWWUTUXWXYcccccccccccc" +
            "ccacdcYXXXVQRROOMNMNHBMLJJJLLLMNMMNNOOPPOQRTSPNNPOPPQNNOPPONONNNNNNOPNNOONNNOPQNOOOOPOOPPQQTRUUVXXVXWXYZZWYXYYYYZYYYaccecbcbbcce" +
            "ccdaZaXXVRQPOPOOMLLJHGGHHHJJLLLMLJJJJJKKLLMLLLLLNRQOOONNOPQPRRQWXWWYZYXUVUQSTVVUVTUTTSQPPPQPPPONRYaQQRQRRRUVWYYaeYYYacYYZccccccc" +
            "cacccYYYVRROONMLLJHFFBBGGHHGFGGHHJJJLLLLMNNONNNTDBGRPPPPPQQQPQUZYRPPQQWRNOPPOPOPNPQQRSSTUPOPQQPOOOWSPRQTRRQQPQTVWVVWceZYacbccccc" +
            "daaYXXVPPPOMMLJJFFEEAACEEEEEEFFFFHHJMMLKMNMNMMNEBBDPGIKIJIJIIINHKLLLLKKNMLMMKLLLRBBCBCCBBNLNNPQTTPOPOONOPQTUTVVVVXYYXYYbccaZeebb" +
            "acaXWVVROOOMJHGFFEDCAABCDEFGHJJJJHGFFHJJJJJJJLKCCFPVEEEFFEEFFFEFFFFFFFFFGFFGGGGGJFDBCCBDBFTNNNONOPQXPPSSQTTRQQQQRSRRTTVXXWYYZabc" +
            "daaYXXWVRRRPOPLFEDCCAAACCCDDEEEEFGHLOOLMNOOMMMNFBDORICBDDDDCDDDDEEEEEEDEFEEFFFFFFFLDCEBGDEPLNONNMNNQUNPOQPPRQRRQTRSRRUVXYacZXZce" +
            "daYXVRPOOMLHHFEEDCCAAAABCCEEEFEDEEJDCDMHGJJJMLOEBEPPGCBGKKKKKKKKKKKKKKMKKKKKKLLLMMMLCBBECDQNNNNOPPPQUPQPPQQRTUVVUUVUVUUUWXYceccc" +
            "aVYXVRPROMLHGEDECCBAAAABEEGMMNLFMJDHLDDNJGGHHKJDBFROGCEIFGGFGFFGGGGGGGIIIIIIIKJIKKKLVNCBCDQJJLLLNNOOQLOPOOOOQPQSQTTRRRRTTUTWYWcc" +
            "aYXURRPLJFEEEDCCBBBAAAAABBBBBBCDFEQefYQKPJNOJNJCBCPMGCFGIGGGGGGGIIIGIIIIIIIIIIIIKKKKLKHCEDRLLLNNLJNLMOHKNLNOOPOOQQQTYXUVWWWXcZcd" +
            "daYWUVONLHHFEEECBBBAAAAABBBBCCCDDCfffffHUONMOVJBCKUJFCFGGGGGGGGGIGGGGGIIIGGIIIKKKKKKLFOABDVOPQRPORTUTWWSVTTVWXXWWWWXXYXYaccZYZZZ" +
            "VRRNNNJGGGEDCCCBBAAAAAAAABBBBBBCPDDHPNHKcHEFGJEDBJYJFCFGGGIIGIKIGIIIIIIKIKKIKKKKIKKKKJFNLQLGHHHHKKKKLLNNLMMOPQQQPOOQRTTUVUVTVVVY" +
            "YWVRONJJFEEEDCCCBAAAAAAAAABBBBBDPfBADFSfaWMEHHCCBKVKGBEGGGGIGEBCFCCDEDDCFCCECEKJKKKKKJEKKWOHHHJJKKJKJKKLLLNOOQPOQQRRTQSTTUUWVYZc" +
            "XWVROOKJHGEDCCBBAAAAAAAAAAABBBDDPQUfffZXeSNFFGJCBKWJFCFGGGGGIDAEBEEBCBCDCADBBFIKKKKIKKFKIUWSSQQLJKLLLLLLLLNLNQQOOQQSQRTTVXXYYXYd" +
            "WQNOLJGEECCCCCCAAAAAADAAAAABBBHADfCBYWbZWKSDEHGCBKUHFEGGGGGGIDADBFEBBBCEBBEFBDKIKIKKKKFKJTZWWWWQJJKKKKLNNNMLKKKLNPOPTTQQTRRUWXYa" +
            "RONMLJHHFEECCCCAAAAAAFAAAAABBBGFBBDKPSPKKWYNNJFBBMTGGFIGGGGGIEBCECDCECDCGBCDBDKIKKKKKKEJJPZWWUUUNHHJJJJLMNNLNPQPPONOPPPQRUVVVVVY" +
            "XVVROPRNMJGEEDDBAAAAAAAAAAACCDHQTDABDGHLYfYYWUFCDNTFFEIGGGGIGIKIIIIIDIFFKKIKKKIKKIKIKKEJINZWUSSSNGJKNOOTWYUNPRQQQPOPWYYXXWXXZdec" +
            "WUQNMJGEEECCCCCBAAAAAAAAAAABBBENPPLLSWZeWdWYWXGBCKPGDDIGGGIGGGGIGGICBCBBKIIIIIIIKIIKKKFJIMeYYWWWTOMLJJHJJJKJKLLMQTONNPPPRQTUUWXZ" +
            "PMLLLJGEEDCBCBBBAAAAAAAAAABBBBHHSNLYbYYYWVWXWYEBFOOIDDKGGGGGGGIGGGIBDBBDIGIIIIIIKKKKILEHKLZYYYWUUNJJJJHHKLKKKKLNNNNNOPPPPQSUVVUY" +
            "VOMJGGGEEDDCBBCBAAAAAAAAAABCBBEDJPLUZYbbQPZXYTDDKWPIDDJFIGGGGIIIIIIEBFDKGKIIKIIIIIIIIKEGKLZWWWUSSLHJGHJLMOOMLLKKKMQTURRQPNOQRUVZ" +
            "aWRNHFEEFEEDCBCBABAAAAAAAAACBBBMOHFQWWSQOdYUXNGBEQOGDDKGGGGGIDEDDDDDEDCEIDDDDFJKIIIIKKGGKKYYWWWUSNGGFGGHHHHHHJJLMMNPPPQQRTVXaZZc" +
            "QOLHHFECCCBBBCBBBBAAAAAABBBBBBCDLQNLNQUWcWWUYQEBFROFDEIGGGGGIDBDBBDBCCBDCDBBBDKIIKIIIKGFKKYYWXWUSPJGGIHJLLKHJKOPKKLLLOSQOQTTTUTX" +
            "RNJHJFFFEEEEEDBDBBBAABAABBEBBBCCBDMOXYZWWSUUSLDBFVMIBEGGGGGGGIBIBBDBBCBDBEBBBDKIIKKIKKHGKKWcWWWWWSNJJKKJHHHJLPPLLLNONNLLNOOPOPRT" +
            "NJHFEDCBBCCCBBJRBBBABBAABBHMDBBBDCCDDFFGHLNNPNDBFWLIBFIGGGGGIFBICCCDDCBDICDCDDIKIKJLFFHDJFPZWWUUSPJFFGFGHHGGHJJKLLLMOPPQQSTUVVVW" +
            "OOJFFGCAAACBBOJLDBBABBABBBJHMDBDBCCDDEEEEFFGLMDCJXMGBFIGGGGGIIIGIIIIIIKIIIIIIKIKKILGCFECFCFZWWWUUUNHHLJJJKLJKKKLLNNNPONNNOOPQUVX" +
            "OMJFFECHJDCCEOFNDBBBBCABBBEDJMDECDDEEFFGHHHGLHCBEWMGBFIGGGGIIIGIIGFFGGGGIGGIIIIIIINFFKKIIILYXWWUUULHFFHGIJKLLLLLLLNLNPQQRUUUVVUV" +
            "NJHFLMPFEJOCFLGLDCCBBBBBBCGBBOCECCCCCCCCDEGFMGCDHXNFBGGGGGGGGIIIGIOMGGIIGGIIIIIKJILJDBGIGGKXXWWUWUPGHHEFFGGFHJKJKKLNNOPOPQPPRRRU" +
            "JHFEMVFBCBWEDMLLCDBBCBBCCCHDCOCRGBEGFFJJNJLMOEEEKYMGBFGGGGGGIGGGGSUeQGIIIIIIIIIKKILKECLLGFHYOWYXWWSMPXOPPQUSWUPNQOQOPPNTTTVWVVVY" +
            "VPMOQNLFEDVPBJLJDDBBCBBCDFQLMDCYSLHJGEGGJMOOPHCDKXJICFGGGGIIIGILNUSWZKFIIIIIIIIJJKLNGNNIIIKXOWYYYYXTQQPOOPPRQOQQVWeXXXVUXYXWWXXY" +
            "JFEFFNJJJROfEBFOOBABFBCEJQOHCBQUOLCCCCCCDEFFNJBDKYIGGGFGIIGGGIILIPbWZVKFIIIGIIIIKIMHCFEDEFFVOUWUWUUKFHGHGHHJJHJKJKPUQLMLOOOPQRUU" +
            "LJLFEMPGGFTVfDBCMEBRVLOVRJEBBWZQNLCBCCDCEEFFJEBDLXIGFIGGGGGIGGGGGKSYSUZNFGGGIIIKKIKNBJFEGFEROUWTSUULGGGHHJKLKLMNNNKOXRPSQQPQTRTV" +
            "LJGHHEJRRYYUUfNCBBEBBCDDCBBFfbUTSOHCCCCDEFGGHEBEMVGFEIGGGGGIIGGGFLZXSWWbNFGGIIIIIKKNcXZWYYZYMQWWWUUPJKLJJJGKKKJKKMQPOYPKNOQQQQTW" +
            "JGFEEGLUXWWeaWffUFBAABBBDOYfXZWQNLCCDEECDCDFJEBEOUGFEIGGIGFGIIGIGIWYUVWSYOFIIIIIJKIIIIKEHIMfVNWUWWUPIFGHJLNLJHLMLLJHLQWRLLOPQUTR" +
            "OLLGHQUUWWWWYeUUdafffaffcYXPXXSQNFBCCCCEFEFJGECEPRIDEKGGIIGIIIGGGGKWZWOUWUNIIIIIKKKKKKIEHKLacXWUUUSPJFFFFHHHHKLNLLOQNPQWWVUSQPOU" +
            "LHGLUSSQSSUWWWYROQVWTWWVRPOVYSQPNEEECCCCCDEFLCBELRIEEKGGGGIIIIIIGGGLUWWcVPXIIIIKIIKKKIKDFKKaXXWWUSUSLJGFGJHHKJHLONSOLMLNPQPQUUTT" +
            "ONLOQSUSPNOSTTVYVNLHJNNMLPaYSSSPCCCCDDEFGGHMHCFOVQICEIGGIGIGGIIGIIGFNNWRWYXQIGIIKIKKKKKDDKIXVYWWWWWWVTPNLLNKKJHHIJJKMNNPQRSSUVYY" +
            "LLKHGJKLNPSQOPQSWYYRTXXXXWSNNKECBBBCBCCCCDDFHFCFRQICFGGIIIIIIGGIGIGKPIOIIOWWSLIKKKIIKIKEDLIXeWUUUSSSNGGHHGGGGJLKKKLLLLOPONMOPPPV" +
            "LJLKHJJJMJJOPONNNOPUWUWTQQPSQJFEEEEFFJOJEGHMMEBGTMICEGIGIIIIIGIIIIKONNQLIIKPQKIKIIIIIJKEDLIUeXWWUUWWPKJHHHHJLLLKNLMLMPQPPQQTTRTT" +
            "ONJJLJDDDHRNQUSQPOOOOOOQONFHFEFFGFFGGGJMONRVKCCKRLIBEGGGIGGIGIIIIIIGGIIIIIGGIIIIIIKIKIKFDLISecZZYWWUWQNLLLKLLJJHHLLLMLLPRQTTRQQR" +
            "QPNKJEAAAABCEEFGGLNNMLJEEDCCCCCCCCCCCCCCCCCFICCKTKIBEIIGGGIIIIKIKKIIKIIKIKJIIKIKMLIKIIKGDLIOZWWWUUSSPFFGOWOFFJHJJHJLLNONNNNNPTWU" +
            "OLKJJPDBBAAAAACBCCCCCCCBBBBCDDDCCEEEEFFGFFHLICDMWJIBEIIIIGBCJBBGBCGCBGDBGEDEEDDCBDKIKKKKEKIOZYWWUUUUSPPTWYaXQQPPQWWSPQQPRQQUXYaZ" +
            "ROONMVSBBBBAAAAABEDCDDCDDEEEFFDDECCDEEEGHJJNGBBMTJFBFIIIKDBEDBBFCBFBBGBAIBBDBBDDABLIKKKKEKIOZWWWUWSSSNLKLKJJHHJKLPQNKMNQVVWWVTPU" +
            "QONMJKQLBBBBAAAAAABCCDCCCCCCCCCEEEDCCCDDEEEMCBKMNIGBFIIGIEBEFCEIDFIKGGCBFEBKBFIEFIIKKKKKDHKMZWWWWUUUSOKHHGJKLLONOLMNOSUTOPQQPOPR" +
            "URNMMMTLBAAABAAAAAAAEDEEDDCCCCCCCDFFGHGHJJKHKEEQWIGBFIGGIIKIKKIIIIIIGIKKIKKIKIKKIKIKKKKMDLLOaWWWWSUTUSNLJKKKKHHJHJLNNNMLOQTVVWVV" +
            "TQRNKJLYHBAAABAAAAAAACCCDDEEFJHGGEDEDEEFFGLMJCENVIEDGIIIIIIIJIIIIIIIIIIIIJIIIIIKKKIKKKKLDBCDTXWWWWWWUTLJKLLKKKLNNOOLNNNQTUUUUUTV" +
            "RTQOMMLOWTLBAABBAAAAAACFDEEDEEDCEEEEFFFFFGJRFCFNUIEEKIIJIIIIIIIIIIIIIIJJJKKIKKKKKKKIKKKMDBECQYUSUSSSSQKHHGHHHKKJKNLKKLLNQPOOPQQU" +
            "XWUUVVQOTYGDBBAABAAAAAAHJLNJNFFJLLMLQRNMJLOPECIOVIDBFKIGIIIIIIIIIIIIGIIJKIIKIKKJKKIKINGEDDDCMZXYWWWWUUNLNLLLLJJLLLNNNNPSOOQVVWXa" +
            "ONNMNLJHLUHBAAAAABAAAAABDDEEEFFFEDEEFHGGJKMLFCGNWIDBBIMLMLMMLMLMLLMLLLLLLMLLNLLLLLMLOCBCBDCBHZWWUUSSSUNGHHHHJKLNLMNQTSSRRUVWVUVX" +
            "VTRQNKKLJLWYGDBAAACBAAABBBGEEEEDGHGHFHJFFGNJECIPVICBCCDCCCCDDDECDDCDDEDDEDDECEEEFEDEJBBFBBFBGaWWUUUSWWSLLJHJJKKKKKMLNNNPRQUTTTUU" +
            "TRRPNJLKJJLQWFBBAAABBAAAAAEFFFEEFEEEFFFFFGNIFCETVFIEGHFFFFFFGFGFFFGFFGGGGFFGFHGGGGHFBECDEHEDEXWWWWUSSSPHHHHHJKLNOONMMPPPOOPPQRUU" +
            "XVUUUQPNNMKLSEBAAAAABBBBAAAJFGGHJHNQQLLLMNRMDBCNRFKKKKKKKKKKLKKLKKKKKLKKLKLKLMKKKKPBBEDDDDDCCYWWUSSSSWPLLLLLMLLKHJJLMOPQSUUUUUUU" +
            "UQNONOMMMLMNSYXGBBAAABBBBAADMEEJGEJMEFFGJLQFCGMGHDFEGGFGJGFGGGHHHGIGJHKLJGKHJKHKJGNBBCBBBBBBEfZZYXWXWXWWLJKJKNNOPQPPNNOOOPQQQTVY" +
            "PONNONONLLKKLNWYWFBAAABBABABEHGGFFFFFGHJJLOCQfXXdYUVXWWWVUWXXXWWWWWWVVUVWWUTUWWWWUWXYXXXXXWVXYWWWWUSSSQKJKLLLLLJJLLNQQQPPQQTVXXZ" +
            "YVVROONMNMKJJJNTNBAAAAACBBBBBOFGHFGGGFGJLPHMYYKLNJDDDDDDDDDDDDCDCDBDDDDEDDDDDDDBDDEFEFGHGFLYZXWWWUTUUSSNLJJKLLLMNPPPPQQQUVWUWWVY" +
            "XXWTQQPNNONLJJGKTfTDBBBAFBBBADKFHJJHHKKGGKJUdTHDDDGHHHJJHDCDCBBCBBBBBBBBBBBBBBBBCDCBBBBDDCKTXYWWWWWUSSWPLNLKHJJKKLNNMMMOOOQQQUWY" +
            "QOONOONNNMNMJLJJMPWbWQEBBDBBBBRFGFFFGHJLLNOUfUHDDDKPRRPRNDDDBBBBBBCBBBBBBBBBBCBDCCCDDCCCDCLRWZYWWWWUUSUTNOPQUSTUTUXXXXZYUVXWXZYa" +
            "WUTTTURONLJJHKJJJJKLTNDBBBHBBLRGJLLJGFFHJMOQZWGEDEFEFEEJOEDBCBBBBBBBBBBBBBBBBBBBBBBBBCBBCCHVVbYYXWWWWWWWQMNNNMMOPQUXeeTQVXWVVVVX" +
            "UWVRRRRQQONLMKHHJJKLNWXTCBDKBFaEFFGGGGGGHKOPXYQTSSHDEEEGXPNNLLLLLLLLLLKLLLNNLLLLNLKLLLNNNNRJQZWWWWUUSSSPLKLMNPOOOONQXPOPSUTTUTTU" +
            "aYYWVTTQPONMNMLNQOONLKQWXUDEKBDXNONNMKJLLHMVPXYTVTMIMMKMXQRQRRQPOOPOOPPQQOPOQTRUQPRPQPWFFFDDXXWUWWTUWWWWOMPNMNNOPOVdQRUURQRTVWXX" +
            "XVVVVVUQPOOOOQTONKJJJJJMPWSSfLCVNHJJHHHHHJKTYVUXaYPIMMLNaXXXXXXXXWXXXXXXXXXXXXXYXWWXXWYQRROWZWWWWWUUWUUUNKLLNOPOORXQRUVUUUVVVUVW" +
            "aXXWVRRRRQQOORMJJLMLJKLKLNSUWeRAFOJJKLJJJJHNYZZeYeMFJFFHfZZYYYYYYYYYYYYYYXXXYYYXXYYYYYXZZYZYWWWYWWWUUSSSQOPQQPUTXfUOPQQTRRTVVWXY" +
            "fYZYYWWWWVVVVVQPPPNNJKJJJHJNSYVMVXKJJKKLMMNLQWUWUYHCGLCMZSUUSSSSSTUUUSSUUUWWWWWWWWWUUSSSWWWUUWUUUSSWWWWXQMNMNNNWYXYeaXXXXXYYYYYa" +
            "cXVUUQPNOONNMMMNMLLMNLJLLKLJLPVfDDHLHHGGGHKLKPUWWWEJWYGNWUWWWWWSQPSUUWUSSUSPPPPQPSSUWWWWSTTWUUWWWWWWWWUQOQRRQPQROPQUXYeeeaXYYYXZ" +
            "ccYXXVUTRQPOONNOPPPOONLNMMNNNLQfEBLNOLMMMMLKJJLOSOOeWWWTWWSNNNNLLLNNNNOONNOLLKLNLOOOONNOMMNQQSTUUUWWQQPNNPQPQUYVTVUUWXYacZZcacec" +
            "ccZZYWWUUTTRRQQUUPNNMJLLJLLKLMLQSEDHTNNNOONNMNNNOOSSTPPSPOLJLLLMLLKLLKKLLLNNNNLLLLLLNNNNNNMLLKLLNOOONOOPPPQQQRXcTTVVXXVXYbeccZac" +
            "ZXVVVVWWURRRTTQQPRQQTRRPPOMLNNLLXfNDNPLKLKJJJLMLLMLMNPSPPQPOOLKNQOMNNNNOQPPPONNMMLLMOONNNNNNNNOQQRRQQPQSRUUTTXfXRUUUVXaccccbcZZc" +
            "cZYXVWXYXVVUURRQPOOMNLLMNMMMMLMMLPZXGQMLLLLLLMNMOOOONMKKLLLKMLLMLLKJKLLLLKJJJLNONNMMMNNNNNNNPQQQQRTRSPOOOOQTXXWTUWYZcecaaccccaZc" +
            "ceaYYXVUUVXXVUTURQPOOOOPPQQQPQQQOOOPVTONNONNNNNNNNOOOOOONMMLNLMPNNOPOONPQQPOONNLLOPQQQQOPQPPOOPNOONONOQUWVXXYWXYYYZcZYYYYcacccZZ" +
            "dccdfYWUVWVUUTRTQQQRUUROPOOPOPQQRQPONONLLLMPPPPPNJLMNNPSSTTRQNNOOORPQRUOMNOOPOPONNONNLLOQTUVVUUSTSTUVYaeccXWYdeeeZZdcccdccecccZY" +
            "ccdddcaYZfYYYXYYYYYZVRQQQPNNNOOONMLMONNNONMMNLLLMPNMNNNLLMLLNNOONNMOMOWPNONMNNNONNNONQQQRRQPQRQPQUVXXeZcYYdYaaaZaZZccbcccZXYccZc" +
            "cceYXXXXWWXXYcXVVUTTTRUWWXWUUTRRQVRTTTVVXUTWYUXXZeTRRRRTWVRVWUXUWXQXfcYffYUVVVUWTTUTVWUTUPQOPUVUWYZaaaacXVXVXcZYZecccccccaZZccac" +
            "cccaaZZYYVUUWVUVTTTUTUUUUTTRQQPQVVVVVVTYZXUQRRPVWRPRVRPVRPPRTRQTVRRQQRRRPUVUVVVVWUURRRRXXXYYXYYYZZXWVVVVVXaaYYZcccccccccbcceccbc" +
            "abccccaXYaYaeYXYYYXWVUTTTTTUUUUUQPPOQPOPONOOOOONNNNNNOOMMOONNPRRQRRRRRQRRRRPQQTUTUVVVVVTRSTUUUTTUWXWVWYYYYXVWYYcccccbccccbbcccec" +
            "cccccaaaadedYYYWVWYaZYXXZYZYXWWUURRQPQRRQUTRQQRRUVVUUVURQQPPPPQRRRRUVVVUURRRQQPPQRUUVWVWWWWWXYYYYYaZZceeYXZaacZccccccceccccccccc" +
            "cbccccccfdaaaaYXXVVUWdYVVUVWXYXXVUQRRTTTRQQQTUUTRRQQPPQQRRTUTRRRRUUURQRRQRRTUUUUUVWVVWYYYYYaeYYcccccccaZcdcccZXcabZccecbcbcccbcc" +
            "ccccaccccaaadaYYfaYYYcYYYYZdfYXYaccZYZZXXVVWXYXWXXXXXYYYYXXXXYYYYXXXYYYXXXXXWWXYYYccceeYYYYZcYYcbcccacccccddcccccbbcecbbcebbZZcc" +
            "bZaccaaaaaaaadfdadfdddddddddaddfdacccccffffffdffeffeececcfffffdcffeccbcccedeffececaccccfffecceecaacccccccacccccbcbcbcbaZbbZZbbbb";

    private LedgerClosedArtwork() {
    }

    static Image image() {
        Pixmap pixmap = new Pixmap(WIDTH, HEIGHT, Pixmap.Format.RGBA8888);
        for (int y = 0; y < HEIGHT; y++) {
            int row = y * WIDTH;
            for (int x = 0; x < WIDTH; x++) {
                int index = SYMBOLS.indexOf(PIXELS.charAt(row + x));
                pixmap.drawPixel(x, y, PALETTE[index]);
            }
        }
        return new Image(pixmap);
    }
}
