package com.shatteredpixel.shatteredpixeldungeon.scenes;

import com.badlogic.gdx.graphics.Pixmap;
import com.watabou.noosa.Image;

/**
 * Embedded palette artwork for the Echoes title flow.
 * Generated from the approved pixel-art source so repository text-only
 * transports cannot corrupt or truncate the image bytes.
 */
final class LedgerOpenArtwork {

    private static final int WIDTH = 160;
    private static final int HEIGHT = 90;
    private static final String SYMBOLS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdef";

    private static final int[] PALETTE = new int[]{
            0xF7DB9BFF, 0xF7D796FF, 0xF6D797FF, 0xF6D796FF, 0xF6D795FF, 0xF6D696FF, 0xF6D695FF, 0xF6D694FF, 0xF6D593FF, 0xF5D593FF, 0xF5D492FF, 0xF4D493FF, 0xF3CF8CFF, 0xE6BB79FF, 0xCFA064FF, 0x9D7342FF, 0x704922FF, 0x523215FF, 0x3F1F0AFF, 0x2B1709FF, 0x221007FF, 0x180D07FF, 0x120905FF, 0x0E0704FF, 0x0B0603FF, 0x090503FF, 0x080402FF, 0x070403FF, 0x060302FF, 0x040201FF, 0x030101FF, 0x010001FF
    };

    private static final String PIXELS =
            "eeeeedcccddccbaaccaaacdccccaaacddddbcccdddddddddccdedddddddcdddeeeddecZcdeccdddddddeeedddcccccddddedeeeeeddeeeeeeeeeeeeeeeeeedeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" +
            "eeedcaaaaaabaaZZYXZacaaaZZZZZaaaaaZZbabcabZbbbZZaZZZZZZZaZZZaZacbbcccZZaZZbabZZZZbbddcbcddcZbccbbbcccddedaacdeeddddededdeddddddeeeedeeeeeeeeeeeeeeeeeeeeeeeeeeee" +
            "edcZYXXXXXXXXXXXXWVWWXXXYYYXXYYYYXZZZaYYXXYXXXXXXYZYZYXYYYZYZYYYZYYYYaaccccYaabZZZaZZZYZZZaZZZaabaaacccddccbccccbcdcbbcabcdccdcddcbcddeeeeeeeeeeeeeeeeeeeeeeeeee" +
            "eecccaaaaXYYZZZaZYXXXXXXXXcaZbcZZaccbcZcbaaaZacaacbcdcbaZaabcZZaaZZacbccdedcdaaccbccaacaaZacccdcddeeeddededddddccddddcdcddddddeedddeeedeeeeeeddddeeeeeeeeeeeeeee" +
            "ecZZXWWWWVWWWWWWXXWYXWXXWWWXYYXWXYXXXXYYWWVWXXXXZXXXXWXYYaYZXXXXYZYYZXXZbdZYYXXZZZYYZZZYZZZZaZZZZbccaaaZZZZZZZaaaabaaaaabcbccdcbcbcccbccdedbbccdddeeeedeeeeeeeee" +
            "dYXXWVVVVVVVVVVVVVWXWWWWXXXWXYXWWXWWXYXXXWWXYYXXXWXXWXYXXXXXXXXXXYYYYYZZYYYZaaYYZZZZYYZZZZZZYXZZZZZZZZZZZaZZbbYYZaaZaZacccbcccccbbcddcdcbccccbcddeedeeeddeeeeeee" +
            "aYXVVUUVUTUVUUUVWWWWVVVWWWVWWVVVWWVVVVWWXWXWWWYXWWWWVWWWWXXXXWWVVVXYYYYYZZYXWWWXXXXXXYXWXYYWWXYXYYaccbZZYYYZYYXYZZZZZZaaaZaaZZaaaZaaZZZZZabcbccccdedddeddeeeeeee" +
            "ZWVVVUUTTTTUUTTUUUVVVVVVUVVVWVVWWVXXWWWWWXXXXXWWXWWWVWWVWWVVWWWVVWWWWWWWXYXXXXXWXXWWWVWWWWWWXXXXXXYYZYYYYYYYXXYYYZYYZZZZZZYZaZZZZZZZeccccdbYZbbbccccddeedddeeeee" +
            "YVUUUTTTTSSTSTTUUUUUVUUUVVSTUUUTTWVXWWWWWXWWYZYYaYWWWXXYYXXXXXXZYcZYZXXYZYXXaZWWWVWWWWWWXXXYabcdccaacbbbcccccccbaabbbbcbZZbYWXXYYXXWTUVVVUWdZZZZZbccacddccdeeeee" +
            "WVUUTTSSSRSSTTTTUUUUUUUVUQQQQQRRRVUUUUUTUUUVWUUUUVUTUVVUUSTUUUUUUUTTUUUUVVTVVXbbXXXYedaWVVUVUUUUVWUTTTTTTUVVVWWXVVVVVUVWXaaWVVVUUWVWRRRRRRRTcYZZZZbbddcbddddeeee" +
            "WUUTSSSRRQSRSSSSTTTUUUTVRQQQQQQPPQQRQOPQPPPPQTSRRSTVUTTSTVUTTTTTTTTTTTVTSTUUUTTUcecbTTTTUUUTTUVUVTSTTUWUUVTTTTTTTTTSRRUSPPQPPPPPPQPQPQRRRRRRZZZZZaacdaccddcddeee" +
            "XVUTTSSSQPRRRSSTTTUVUUUYQQRQQSROOPNOONNONNNNOPONNOOQPOOOOPPNONOOOOONNOPNOPQQQTUVTSTTUUTRQQQOOQQPPOOOOPQPPPNOONONOONONOPONNNONNNNOONNNQSRQSSRZdddddddeeeeddeeeeee" +
            "XVUTSSRSQOQRSSSTTUUUVVVWQQQQVRPOOONMNNNNNNNNNNNNNNNNNNNNNMMNNNMNNMMNNNNNNNNNOOPQSVUURQONNNNNNNNNNNNONNNNMMNNNNNNNNNNNNNMMMMNMNNNNNOOOPQWSRRQYcaZZbbadddeedddeeee" +
            "VUTSSRRRPAPQRRRSSTTTTTUWQQQQSPPOONMNMMMMMMMIHHIMKBMKLIJGIKKKICCHKKKKEIMMMMNNOOOPPTWQOOOONNMMMJLMKHKMHKLGKKKKKKHMMKKIIGEKIKKMMMMMMNNOPQQRTRRRWfccZZZZbbbcddddeeee" +
            "VTSSRRRQOAOQQRRSSTTTTTVXPQQRQPPONMNMMMMMMJHJKKKMJHHHJHKKJGHJJGKKKHHKKJJKMKKMNNOPPQRPOONMKMKKKGFGJJKKGCGGKKKMHDGKMKKKJJKMHKMKMMMMMNNNOPQRRTRQUfbcbZabaaccaddbceee" +
            "UTSRRRQQKANQQQRRSSSTTTVTPQQRQPPOMBNMMKKCDKKKKEJDHJKJJJKKKJGGGJKKKKJDDJGHJHKMNNNOPRRPONNKIKKJHGDHDKHJKKGGEHKJKKKKMKJKEJKKJJKMKMMMNMNNNPPRSSRQTfbcbZadddcbabddeeee" +
            "UTSSRRQQAACQQQRRSSSTSTVSSTUSQPONNMMMMKJKKKIGJHJGJJHJKKKKJHIGJJJKGKKHHGJKKKKMMMOOPQRPNNMKKJGHJJHEJKKKKKJKKKGHKKKKKJDHEKKJGKKMKKMMMMNNOPPRSVUTVdbbbZZZabZZaabcdeee" +
            "UTSRRRQQNACQQQRRSSSSTTUcTSTRQPONNMMMKKKMKIDDGGDDGKFCGHKDJIGJDJHDJDKJGDKJDGKMMMOOOQRPNNNMJHHKKJJIKJKKIJKKKHJKKKJDKGJJHGDHKKKKKKKMMMMMNPPSSVUUaeeeddcccbdeecdeeeee" +
            "UTSSRSPNNPNMPSSSSTTTTUVXSSTRQPONNMMKKHDDEGCGJDDEDGKHEDHJGCDKGJJHKHJIDJHDHKGHMMNOOQRONNMKGGDJHGHKKDJJKJKGCGKJHJKKKKJKJEKKJKKJKKKMMMMMNPPSSVUUaeeeddcccbdeecdeeeee" +
            "VUTSSQMNMPNNNPSSSTTUUUVWSSTRQPONMMMKKJKKGDEGGFGEJGHJFDGDDHJGHJGJKMKHEEHHGKMKKMNOOQROONMKJKKKHDGGKKDIKHDEGGJKIDKKKKKJKDKJDHKKKMJKKMMMOPPRSWUTXfdddbbccccdceddeeee" +
            "UTSSSQMNNPONBPSSSSTTTUVVSSSRQPONMKJKJKKJJGGHDJHGKDDGDDDDDJJHCDEHHHKJGDGGGGHEMMNOOQRONNMJDKKKDDDDGKIJKHEFGKKKMKKDGGIKKDIKHKKKKMMKKMMMNOPQSWUTWfbbbZZZbbabccddddee" +
            "UUTSSRONNONNOQTSSSSTTUWVSSTQQPONMKGJIDDDJJDDGKGHJDEJHGDDDDGDDDDDJHGHHDDDDDDEKMNOOQRONNMKJCHJDGDDDEJGDGHKJJKHDJIGHDKHHGKJGIKKKKKJKKMMNPPQRWUTVfbbbZZZZZZZZaaadeee" +
            "VUUTTSPPONOPPQTSTTTTTUXUSSTQPPOOMKKHDGHJJCDKKJHGGHGKGCHHDDDDDGDDDGJJCFKGDGKKKMNOOQRONMMKHIJEDJDDEDDGGCGKKDJKHEDJKKJHHGKKDHJJKKKKKMMMNOPQSVUTVfdbcbbaabZbcccdeeee" +
            "VUUTTRPPPOPPOQTSTTUUUVXTSSSRQPONKJKKJKJJDDJKKJKHDDEJGGDGGGDDDDJGDGGEHDGKDGKKKMNOOQQONMMHDJGDGDGDGGGDDJKEDDDDJGGDJKEJKKKHGJGHKHHKDKMMNOPQSVUTVfdbcbacaZZbccddcdee" +
            "VUTTURPQPOOPPQUSSTTTTUWSRSSQPPNNKKKKJGIJDDJEJJKDDDDGGHHDGDDDDDGDDHDDGDDDDDDEKMNOOQQONMKKCEGDDDDGDDGGHJEDGGDDGHGJKEHJKEHGGHJKHHKKMKKMNOPQRUUTUecbcbabZZbcccdddeee" +
            "UUTTURQQPPOPPQRTTSSTSTVTSSSQPPNNKEKJJJGFDDDDDGDDGDDDGDDDDGDDDDDDDHDDDDDDDDDGKMNOOQQONMJHDDGDDDDHCHJJKGDDKHDDDDDHHDHFDIKHDGJKGDGHKKMMNOPQRUUUUcebbbZZZZZZcdddddde" +
            "VTUTRQQQQPPPPRQQTTSSSTWSSSSQPPNNKKKHDGHHGGDGDGJDGHDHDDDGDGGDDGGDDDDDDDDDDDHJKMNOOQQONMKHDDDDDDGEHEJIGEDDDGDDDDDGGDFHHKJDFGJHKKHJIKMMNNPQRTVTUcebbbZZZZZZbbbcbbde" +
            "VUUQQRRQQPPQQRRQQSSSSUVRSSSQPPONGKKIDKKEKKGDDDGDEGGJDDDDDDDGJEDGDDDDDDDDDDHKJMNOOQQONMMDDGDDDDGDDEHGFDDDDEDDCDDKHDCKKKHDDGGJKKKJJKKMNNPPRTVTTYebbbZYZZZZZZbbcbce" +
            "VWQQQRQQQPPQQSRQQQWTUVURSSRQPONMHKKJGKKECGDKGCDDGGDGDDDDDGJDGDGGGDDDGDDDDDDKIMNOOQQONMJDDDDDDDEGFDDIHEDDDGHDJKEGDCEGJGDDDJGHGGJHKKMMNOPPRTVTTWfccccZbZYccbcdddde" +
            "eSQQQSRRRQPQRSSQRPTUUXVRSSRQPONMKKJHDJDDJJGKGJKJGGGHGEDDDDHGGDGDKGDDDDDDDDCJKKNOOQQONMKGGDDDDDDDGDDGDDDGDHDJKKJJJDJGGGJJDGGKGJKHJJMINOPPRSUTTWfddecaddccddddedee" +
            "eRRRSUTSSQQRSUTRQPSTSUSRRRRQPONMJHKGGDGJHGDHHJHGDGGDHHGHDHDJGDDDJGDDGDDDDEHGMMNOOQQONMKJGDGDDDGDDEHGDDHHDJGGDDHHKKHKJDDGIKIHGGKKCJMINOPPRSUTTVfbbcXXZZYZZZZZbZde" +
            "fTQTSTXUUSQSUVSRQQUTTVSRRSQQPONMHDGFJHGHEGIJHDGDDDGGGDDGEGDGDDDDDDDDDDDDDJHHKMNOOQQONMKGDGDDDDDDGDEGDDHGGDDCDDDCGHJKGCGJKKHCDHKHHJKKNPPPRRVTTVecbbbaZZZZbabcccde" +
            "cXRSSTVVVRQSTTRQPRfTSVSRRSRPPPNMHIDGDDDCEKJDCJJEGEHDDGDDDGDKIDGDGEGJIGDDDDDEMMNOOQQONMKHGGGHDDDDHDDJGDDDHEDGGDJHCJJDGHDKJHHJGJJGKMKMNOPPRRVTTUecbbaYZZYZZZZZZbde" +
            "afVRSUTTSSRRRQQQQcWTTVSRRSRPPPNNMKIGGDGGHGJHJJGDDDEJGDDDGDDDEDDDGKKJHEDDDDDDKMNOOQQONMKHEDDHDGDDDDGDDDDEDGDJIEKJJGDFGGDGKKEKKGKJKMMKMNOPRRUTUUedbbbZYYZYZbbbdeee" +
            "bcfUSSSRRQPPPQQQXcWUUWRRRSQPOONMHKMGJKIJJJHEDEDDEDIJHHHDGDDGDDDDDKKDGDEDDDDEKMNOOQQONMKJEDDDDGEEDGDIGDKKHDKJDGJJGCGGDDEJJEKKIJMDKJKKMNOPRRUUUTceccbZZZbcdcbbccde" +
            "ZZdeXTRQRPPQQQSYcYUTVVRRRSQPONNMJDHJGCGGDEDDDJEDHGJGGEJHDGGDDDDDDJHDGGDDDECIKMNOOQQONMKDDDHDDDGGDGKKGDJIKIGGDDJJHDDDGDDJHHCHHDJJKHKKMNOPQRUUTTaecbbbbaaabZabbbde" +
            "YYZcefXWTRRSVafaXUSSUURSRRQPONNMMKHKKGIDGDDDDGHHCDHDDDEGGEGDDHGGGJHGDDDDDGEKKMNOOQQONMKIDDEDDDGDDDGKDDCDEKDDDDGKJDDHKGEHGEHGDGCMKKKMMNPPQRTUUTXebbbZYYYZZabbabcd" +
            "WWWYZbcceeefdZWVVTSTVURRRRQPPNNMKMJJKJDDDDDHHHIGDDDGDGDEDDGEGHJGJGDDDDDDDGFKKMNOOQQONMKGDDDDGGGGEDDDDDDDDJEKKCGDHGEEGGJCHJDHJDGDHKKMINOPQRTUTTWfbbbYYYYZZZZZZbce" +
            "WVVXXXYZaZbYWVVUSSSTVTRRRSQPPONHJHKJDJDDGDDDGGEDGDDDDDDDDDDJDDDEGDDDDDDDDDDJKMMOOQQONMKGDDDDDDDDDGDGDDDDGIGHJDGDGGEDDHHGHHGJDEDDJKKMMNOPQRTVTTVfbbbZacbcdccdbbde" +
            "XVUVVVVWWXWVUUTSSSSTVTRRSRQPONMKKJHDDGHDDGDDDGGDEGDEDDDDDDDGDDDEEGDDDDDDDGGDIMNOOQQONMJGDDDDDDDDDGDGDDDDGIGHJDGDGGEDDHHGHHGJDEDDJKKMMNOPQRTVTTVfbbbZacbcdccdbbde" +
            "WVUVUVWVUVUUTTSSSSSTWSRSSSQPONMHJEDGJJDDDDDDDDHGFGDHDDDDDDDDDDDEDDDDDDDDDDDDJMNOOQQONMIDDDDDDDDDGDDDGDDDDHHHDDDDDGGDDGJJDGDCDDHGEHJMMNOPPRTVTTUfcbbbYYYYYZZZcbde" +
            "ZXVUUUVVVVUTTSSTTTTVXSRSSRQPPNMHDDDGGHDKJDHJDDDDDDDDDDDDDDDDDDDDDDGDDDDDDDGGKMNOOQQONMKHHDDDDDGDDDGHHFDDGGDGGGJGDDDGHJJJDGDDDDDHKKKKHNOPPRTVTTTedcbbYabcbccddcde" +
            "XWVVUTTTTSSSSSSSTTUVXSSSSRQPOOKHGHJGHGCIEDDDHGDGDGDDDDDDDDDDDDGHDDDDDDDDDDJGMMNOOQQONMJHJDDDDDDDDDGJDDGGDDDDDGJHDDDJGCJJDJJHJGDGJJKKMNOOPRTVTTTddcbbZaccccabdcde" +
            "WVUUTTTSSSSSSSSSSSTUWSSSSRQPONMKDJGGDDGDDDDDHHDDDDDDDDHDDDDGGEGGDDDDDDDGGDDDKMNOOQQONMKECDDDDDDDDDDGDDDDDDGDDDDDDDDGDJEGGFGEGDFKDDJKINNPPRSVTTTaebbbZYZYZZZacbbd" +
            "XVUTTTTTSSSSSSSSSSUVWSSSTRQPONMKGKDDDDGDDGGDDDHDDDDGGDDDGGGJDGGDDDDDDDDDDDHIKMNOOQQONMKHGDDDDDDDDDDDDDDDDDDDDHJEGJGGHGHGCGDDDDHJGJKIENOPPRSVTTTZebbbZZZZZYZaZbbc" +
            "YWVUUTTTTTSTTSSSSSUWUSSSSQQPNNGHJKGHEGDDGDDDGJDDDDDGGDDDEEDDDDDDGDDGDDGGDDJJKMNOOQQONMJKGDDDDDDDDDDGDDGGDDDDGJDGIJKJGGKJGJJGHKHHJHJKEMNPPRRVUTTXfcbbZZZZZbbccbcd" +
            "ZWWWVUUTTSSTSTTTUTVYUSSSSRQPNNHKHIGDGHDDDDDGEKGDDDDDDDDDDDDDDDDDDDDDDDDDDDDJMMNOOQQONMKDDJGDDEDDDEGDDDDDDDDDDEGDGHKHDDGKGDHDDCHKDIJKJMNPPRRVUUTWfdcbbZbbcdcbcddd" +
            "ZWWVVUTTSSSSSSSTSTVXUSSSSRPPONEJHKGEDDEDDDDGGDEGDDDGDDDDDDDDDDDDDGDDDDDGDDDHKMNOOQQONNKEDHDDDDDDDGGDDDDDGDDDDDDDDHDEEGDGDDGKKEJKGKDMEMOOPQRVUUTVfdcbbZZZcccacdde" +
            "YWVWWVUTTTTTTTUUSTVYTSSTSQPPPNMKJJKIGHDDDHGHJGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEKMNOOQQONMKEDDDDDGDDGHGDDDDGDDDDDDDDDDDGHFGJGDGJKKIJJGGMKNNOPQRUUTTVfcbbZXYXZZZbbcde" +
            "YXWVVVVVVUTUUTTTUVWZTSSSSRPPONMKICJKFDDDDDIEDDDDGDDDDDDDDDDDEDDDDDGDDDDDDDHJKMNOOQQONNMDDDDDDDDDGGDDDDDDDDDDGGJHGEDDJJJGDDHGGJJKMJKMMMNPPRRUVTTVfdbbbYYZZZaaZZcd" +
            "ZVVVVVVUUTSSTTTUUVXYSSSTSQPPNMEKHGIIGHHDEGKIEDDGGDDGDGDGDDDDGDDDDDDDDDDDDGDIKMNOOQQONMGHGDDDDDDDDDHGDDDDDDDDGHJGJKGHIKGEDDJKHJKKJHJKKHNPPQRTUTTUddbbbXYYYYZYZZcd" +
            "YVVVVUUTTTTTTUUUUVXXSTSTRQPPNMCJDDHKEIHKEJHEDDGGEDGGDDDDDDDDDDDDDDDDDDDDDDDHKMNOOQQONMKHGDDDDDDDDDDEDDDDDDGGGEIGKGJIEGGEDDIKJGJHJKHKLKNOPQRTUTTTdebbbXWXYYZZZZce" +
            "cXWWWWUUUTTTTTUUUWYXSTSTRQPPNMDDGEEJICJKEHGDDDDDDGGDDGDDDDGDDDGDDDDDDDDGDDDHKMNOOQQONMKGDDDDDDDGDDDIGDDDEDHJDEDGDHJDKDDDEHDEJHFJKKEMKKNOPQRSVTUTcfcbbZZbbZZZabce" +
            "ZbZWVWZWVUVVWWXVVYdWTTSTRQPPNNKCKJGKDKGEEDGGDDEGDHDGGGHDDDDDDDEEGDDDDDDDDDGIKMNOOQQONMJDDDDDDDDDDHGIEGGDDGDHEGHHHGHKHDDGHGKKKKGHIKKKMMNOPPRSVTUTYfbbbZXZZbdeccde" +
            "aXWVUVVUUVVVVUVVVXcVSTTURQPONMMGHHGDGKJDDDHJGDHGDDDGHKGDDDDDDDDDDDDDDDDDDDJHKMNOOQQONNKDDDDDDDDDDDDDDDDDDDDDDDHGJHJJDGHGDHGJJGKKJKKKJMNOPPRRVUUTWfbccZZaZXZaaade" +
            "XWWYYYWVVUUUVVVUUVZUTTTTQQPONMMKHJEDHHGDDGHEDDDHGDDDDGEDDDDDDDDDDDDDDDDDDDDHMMNOOQQONMJDDEDDDDDDDDDDDDDDDGGDDDDDDDJDGEEHHKHHIDKIGHJKMKNOPPRSVUUUWfcbcbWXYZYYZbbc" +
            "ZZYYXWVUVVVVVUUUVWaTSTTTRPPONKKKKDHHHDEGDDGGHKDGGGDDDDDHHDDDDDGDDDDDDDDDDDHKMMNOOQQONMDDGGDDDDDDDDDGGGJFHJDDDDDHGGDDHKJDGGGDJKKDHJKGMMNOPPRSVUUTVfcbbZYYZabbbbbc" +
            "aYXVVVVVUVVVVUVVVWeTSTTTQQPONMJKDGHJHDDGHDGKGCGDDGDDDDDHIFDDDDDDGDDDDDDDDDGKKMNOOQQONMKGDDDDDDDDGDDDDDDGGEEGDDDFDGJDDDGEDDHGJHHJHDGKJMMOOPQSVUTUVfcbbbZXXXXZZZce" +
            "aXWVVWVVVUUUUVUUVaaTTSTTQPPNNMKJDGJFDDDGHDGCDGDDDDDDDDDDDDDDDDDDDDDDDDDDDDFEMMNOOQQONNMIDDDDDDDDDDDDDDDDDEGDDDDDEGEDGDDDHHDJHDKGDGGHJMMNOPQRUVTUUedbbbWWWWYYZZbe" +
            "bXXXWVVVVWVVVUVVWZXSTSTSQPPONMMKJJJGDJDEDDGIDDGDDDDHGGGDDGGEEDDDGDDDDDDDDGDJMMNOOQQONNKGDDDDDDDDDDDDDDDGGDDHDDDDGDHGDHJIHJHKHKHDDJJJKKMNOPQSUVTUTddbcbXXXYZZaZbd" +
            "cddcdedcbbXZdZaccdXTTTUSQPPONMMMGJJDGGDDDDGJGDDDDDGDGJDGDDDDDDDDDDDDDDDDDDJKMMNOOQQONMKHDDDDDDDDEDDDDDDEEDDDDDDDGGDHIKKHHJHGHHJJHJKKKKMNOPQRTWUUUceeeeedcedeedde" +
            "dcXXVWVWVUUUVUUVYbVSTTURQPPONKKMIGJGDDDDDDDDDDDGDDDDDHDDDDDDDDDDDDDDDDDDDDGGMMNOOQQONMKIDDHDDDDDGGDGDDDDDDDDDDGDDFDGEDGJEDDHGDGDJHKKKMMNPPPRTWUUUaecccZZcZZcccde" +
            "cZXXXWXVVVVVUUUVVYVTTSURQPPOMMJKJEHGDDDDDDHDGDDEDDGGGDDDDGDDDDDDDDDDDDDDGDDHKMNOOQQOONMDDGDDDDDDDGEHGDDDDDDDDDGGGHDDDDDHJEDHHDDDJHKMMMMNOPPRSWUUTYebbbZYZZZZZbdd" +
            "bZYWXWVWWVVVVVVWXcUTTTVRQPOOMMMMMDJEDDDDDEKHDDGDDDDDDDDDGKHCDDDBDDDDDDDDDGEKMMNOOQQOONMGDDDDDDDDDDGEDDDGDDGDDDDJKIDHGGJHDGDDHDDDDKKMMMNNOPPRSWTUUXfcbbbZabbZZZbe" +
            "ZXWWVVVVWVVVVVVWYfUUUUTRQPOOMMMMKKKKCEDJIHGDDDDDDDDDDDDDCGJJDDDDDDDDDDDDGJHKKMNOOQQOONMHKGDDDDDDDGDDDDDDDDEGDDGJFGDDGGGGDDDGJEHEKJKMKMMNOPPRRWUUUWfcbbaZXYaZZace" +
            "bYWWVVUUUTUUUUUWcTQQQRTRQPOOMMMMMKKHDDDKKDGJDEDDGGJDHDDDHHJGGEEDDDDDDDDGGDDJMMNOOQQONNMJGDEDDGDDDDGDDDDDDDDDDGGGKJCGKGDCDHJKDGJKKKMKMNMNOPPRRUTTTTdcbbaYXXYZbZce" +
            "bZZXWWVVVVVWVVVYdRPQQQSQPPOONMNMMMKHKKJDGGHHGGIDEGGKDDDDJHIDDDDDHGDDDDDHKKKKMMNOOQQOONMMKJGDHDDDDDDGGDDDDHDEDGIGEDDDHGHKJCEKMKKMMMMKMMMOOPPQRUSRRQSfceeaXYZZZccd" +
            "bZZZbYYYXVVVVVVWfQQRQRSQPPPOOKMMMMKMMKKJDDGGGGHDGJJKGGDCDGIEDDDDGGDDDDDHKKKKMMNOOQQOONMMKJGDHDDDDDDGGDDDDHDEDGIGEDDDHGHKJCEKMKKMMMMKMMMOOPPQRUSRRQSfceeaXYZZZccd" +
            "bYWWVVVVVVVVVVWZcQQQQSSRPPPOPNMMMNMMMKMKDGEKHHJHJKJGIHGKJDDHJHJJJDGEHGJKKJMMMMNOOQQOONMMMKKJJJKDDFGGGDDGKKKHJJJJJEHJJMKKJJGKKKMMKMMMMMNOPQPQRTSQRQSfZbcZXYbbbdcd" +
            "ZZWWWVVVVVVVVWWYYQQQQSRQPOPOOONNMMMMMMMIEMMIHKKHGJHJKIKKECHEBBBIEBBBBEBEEEKMMNOOOQQOONMKMKCKKEBCBBCCECCBCGKMKJKMKEKKJKMMMMKMKMMMMMNNMNOOOPPQRTSQRQRfcbcYZYYZZZbe" +
            "aZYXWWWWVVVVVVVXXQQQQRRQQPPPOPONONNNNNNNMMMMMMMMKMMMMMMMMMMMMMNNNNNNMMMMMMMNNNOOOQQOONMMMMNMMMNNNMNMMMMMMMMMMMMMNMMMKKMMMMMMMNNNNNONNOOPPQOQRTSQRQRcdccZZYZZZcbc" +
            "abZXXXXWWWVVVVXaWQQQQSRQQQPPPPPPPPOOONNNOONNNOONONNONNNNNNMMNNONNNNNOONNNNOOOOOOOQQOONNOONNNNNNNNOOOONNNONNNNNNOOOOOONNNONNNNNNNOOOOPQPPPOPRRTURRRRddbbbZZZZabbe" +
            "ZbZYYWVWVVVVVVXdTQQQRTRQQQQQQQQQQQQQQQQQQQPPPPOOOOOOPPQPPPPPPQQPPPPPQRQPPPQPOOOPPQQPOOOOOPPPQPPPPQQQRQPPPPPPPPPPPQPOOOOOPQPPPPPPQQQQQQPPPQRQRSURRRQYebcZYZZZbbcd" +
            "dcaZcZZcYWYXYXZfSQRQRSRRSRRRRRRRRRRRRRRRQRRRRRQRQQQQRRRRRRRRRRRRRRRRRQQRRRSRQQPPQSSQOPQRRRRSRRRQRRRRQRSSRRRRRRRQRQQQQQQQQRRRSRRRRRQRRRQRRRQQRSURRRRWfddbYcccbdee" +
            "ddaZbYYYcXWXWXYdSQRQQSSTTSSSSSRRRRRRRRRRRRRRRRRRRRRRRSSRRSSSSRSSSSSSSRRRRRRRRSTRRSRRRTSRRRRRRRRRRSSSSSSSSSSRRRRRRRRRRRRRRRRRRRQRRRRRRRRRRSSSRRURQRQVfceeccccddde" +
            "bbXWWWVVVVVUUVVeRQSRQSVUVVVVVVVVUUVTTUUVUTTTTTVVVVUUVUVVVVVWVVVWWWWWVVVTTTSSTTTVSRRTUSSSSTTTUVVVVVWVVVWVWWWVVUUUTTTUUTTTTSSTSSSRSSSSSTTTUTUUVUTRQSRUfbbbYZZZZcde" +
            "cZZYXXWVWVVWVWWcUQQQQQQRQSVTUUUTTUUUUUUUUUUUUUVUUTTTTTTTTTTTUUUUUUUUVVVWXXWVVVVXTSTUVUVVWXXXVVVVUUUUUUTUUTUUUUUUUUUVVWVVVVWWWWWWVWVVVVWXXYTSSTRRSRQVfcbbaZZZbcee" +
            "cZZZZYWVWWVVVWVZZTSSRRRSRSVUUUUUUUUVUUUUTTTTTTTTTTSTTTTTTTTTTSSTTSTTTTTTTTTWZdXfUTTVfccWUTTTTTTSSTTSTTSSSTTTTTSTTTSTTTTTTTTTTTTTTTTTTTTTTVQQQQQRRQTbebbbZZacccee" +
            "cZZZYWXXWWWVWYWbdXYWWXXXXWddddddeddddddddaZbdZYYZYZYZZYZZYZYYYYWWWWVVVVVUUTTTVVbUSTVdWUTUTUUUVVVVWXWXZZYZYYXXYXXXXVVVWVVVVWWWXWWWWWWVVVVVWTUUTTUVVWdebcebbdcdcde" +
            "ddbbZYZYZYYXWWYYbedeeeeddeeeeeeeeeeeeeeeeeeeeefefeefeeffffffffffefecddddccbXUUTUSSSTUTUXXacZcefdcfefeeeefeefeeeeeeccccccdcdeedededcedcdeddYYXXXXZZceeddcZZbbbbde" +
            "dcbbbbccXXWWXWXYYcccdccdddcbcccdddcdcccccccccccccccddcccdccccccceddeeeeeeefedYXZTSSUXYceeeeefeeeeeeeeeeeedddddedeeefeeefeeeeeeeeeeeeeeeeeeffffffefeeeeccbZZbcdee" +
            "caZYXZZYXXWWWWWWWXYYYYZYYXYbZYZYYYYYYYYZZYbZZbbZbZbbccbbbZZbZcbbcabbccccccddcddfTRRTfdeeededdccccccddccddcbccccccbccdcccbbbbccdccdccdbccdddededdedeedccccZZbccde" +
            "cbbYZZZXWWWVVVVVVVWWVWWVVVWYWWWVVVVVVVVVVVWWWWWWWXabYWWWWWWWWWXYXXYbbbbZbccdccbfSSSTfabdeddcbbbbZZZZYZYYZYZYYYYYYbabYYZbbcddZZZZZYbbZbbbbccbbbbbbabcccdddeddcdde" +
            "dbcccbcZZYYXXXXXWWWWYWWWYZWWVVVVVWXWVVVVVWVWXXYYXXXWVVVVWVWVWVVVVVVWWWWWXYXXYYYZTdaUcbZYXXWYYXXWWXXXWWXXXWWXXWWXYXYXYXZbYYXYXXWXXXZZZZZZZZZZZZZZZZZZZZZZbaceeeee" +
            "dddccYaYYYYWWXXXXWWWWWYYYXWWWWXXXYXWWYXXYYYYYWWWVVVVVWWVVVVVVVVVVVVWVVVVWXWVVVUUYXWcWWWVVVVVWXWWWWWWWXWXWVVVVWYZZZZbbbZXXXXXYYYZXXXZZZZaZaZZZZZZZbbZZZZZZZcdeeee" +
            "eeeeecbZYZZWXYXYXYYYXYXWWXYZZZYXWVVWXXYWWXWXXWWXXXXWVVVVVVVVWWWWWYXXWVVVVVVVWWWXXVVWWWWVVVVVVVWWWXWXZYYYXXXYXXYaYYXXXWXXXXWWYYZaXYYacZZZZZZZZZZZbaZbcccdcdeeedee" +
            "eeddeeddddccccXZZXWWWVWXYYXWXXWWXXXWWWXWVVWWWWWVVWWWWWXXYXXWWWWWWWVWWVWVVVXXWWWWWXZYWYZYYYXXWWXXWWXXWXWVWZXXXXWXXXXXXXXXWWYZZZXZZbcbcbZZZZZZZbZcccdccceeddeeeeee" +
            "eeeeeeedcbZabbbbbbbcbZbbbbYYZZZYYXXXXWWWWXWWWVWWWWXXYYXYWWXXWVWWWWWWWWXWWWXWWWXXWWYWWXZZZWWXWWXXYYXYXXYYYYYZZYYYYZZXXXXYZbbZZaZYZZZZbbZZbccZbbbbcccdccdddeeeeeee" +
            "eeeeeedeeeeecbbbabbbbbbbZbbcbaababbabaYZZbbcbZbcZZaZZYYZYYZZbZZZZZbYZYYaaZaZZbaabbZaZabaZZZbbbbbbZZbbZbbabcbbbcbaabcdcbcbddcdccdedbbddddbeededdddedeeeeeeeeeeeee" +
            "eeeeeeeeeeeeeeeeeeddeeedddeeeeedeeeeeeeeeeeededddddddeddeedddededeedeedddddddededddddeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedeeeeeeeeeeeeeeeeeeeeeee";

    private LedgerOpenArtwork() {
    }

    static Image image() {
        Pixmap pixmap = new Pixmap(WIDTH, HEIGHT, Pixmap.Format.RGBA8888);
        for (int y = 0; y < HEIGHT; y++) {
            int row = y * WIDTH;
            for (int x = 0; x < WIDTH; x++) {
                int index = SYMBOLS.indexOf(PIXELS.charAt(row + x));
                pixmap.drawPixel(x, y, PALETTE[index]);
            }
        }
        return new Image(pixmap);
    }
}
